# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bi-ios-2018' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bi-ios-2018
  pod 'SnapKit', '~> 4.2'
  pod 'Alamofire'

  pod 'FirebaseDatabase', '~> 5.0'
  pod 'CodableFirebase', '~> 0.2' # https://medium.com/@alickdikan/easy-custom-models-and-firebase-in-swift-4-with-codable-43bdb7805b31
end
